In [2]:
import gym

In [3]:
env = gym.make('FrozenLake-v0')

In [4]:
obs = env.reset()

In [5]:
obs.shape

()

In [6]:
env.action_space

Discrete(4)

In [7]:
def move(e, action):
    e.step(action)
    e.render()

In [8]:
move(env, 1)

  (Down)
SFFF
FHFH
FFFH
HFFG


In [102]:
env = gym.make("Taxi-v2")

In [103]:
env.reset()

171

In [104]:
env.observation_space.n

500

In [105]:
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [106]:
env.action_space.n

6

In [107]:
env.env.s = 11
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [108]:
env.step(1)
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)


In [109]:
state, reward, done, info = env.step(1)

In [110]:
print(state, reward, done, info)

11 -1 False {'prob': 1.0}


In [111]:
env.reward_range

(-inf, inf)

In [112]:
state = env.reset()
counter = 0
reward = None
while reward != 20:
    state, reward, done, info = env.step(env.action_space.sample())
    counter += 1

print(counter)

17850


In [113]:
import numpy as np
Q = np.zeros([env.observation_space.n, env.action_space.n])

In [114]:
# total acc reward for each state
G = 0

In [115]:
alpha = 0.618

In [116]:
for episode in range(1,1001):
    done = False
    G, reward = 0,0
    state = env.reset()
    while done != True:
            action = np.argmax(Q[state]) #1
            state2, reward, done, info = env.step(action) #2
            Q[state,action] += alpha * (reward + np.max(Q[state2]) - Q[state,action]) #3
            G += reward
            state = state2   
    if episode % 50 == 0:
        print('Episode {} Total Reward: {}'.format(episode,G))

Episode 50 Total Reward: -560
Episode 100 Total Reward: 14
Episode 150 Total Reward: -205
Episode 200 Total Reward: -7
Episode 250 Total Reward: -4
Episode 300 Total Reward: 13
Episode 350 Total Reward: -4
Episode 400 Total Reward: 6
Episode 450 Total Reward: 10
Episode 500 Total Reward: 7
Episode 550 Total Reward: 3
Episode 600 Total Reward: 7
Episode 650 Total Reward: 9
Episode 700 Total Reward: 7
Episode 750 Total Reward: 10
Episode 800 Total Reward: 11
Episode 850 Total Reward: 6
Episode 900 Total Reward: 13
Episode 950 Total Reward: 7
Episode 1000 Total Reward: 9


In [117]:
Q

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-4.26094938e+00, -4.32600000e+00, -4.60798739e+00,
        -4.32600000e+00,  2.69934246e+03, -6.18000000e+00],
       [-3.68863072e+00, -3.70800000e+00, -4.06864028e+00,
        -3.70800000e+00,  2.52725209e+03, -6.18000000e+00],
       ...,
       [-3.09000000e+00, -3.24094572e+00, -3.09000000e+00,
        -3.59652939e+00, -6.18000000e+00, -6.18000000e+00],
       [-3.70800000e+00, -3.90150370e+00, -3.70800000e+00,
        -4.39314533e+00, -6.18000000e+00, -6.18000000e+00],
       [-1.23600000e+00, -1.23600000e+00, -1.23600000e+00,
         6.78440400e+00, -6.18000000e+00, -6.18000000e+00]])

In [118]:
Q[:5]

array([[   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [  -4.26094938,   -4.326     ,   -4.60798739,   -4.326     ,
        2699.34245577,   -6.18      ],
       [  -3.68863072,   -3.708     ,   -4.06864028,   -3.708     ,
        2527.25208951,   -6.18      ],
       [  -4.73295813,   -4.944     ,   -4.89831904,   -4.944     ,
        2622.24454333,   -6.18      ],
       [ 292.29961128,   -9.27      ,   -8.82361075,   -9.27      ,
         -12.36      ,  -12.36      ]])

In [119]:
state = env.reset()

In [120]:
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [121]:
action = np.argmax(Q[state])
print(Q[state])
state, reward, done, info = env.step(action)
print(done)
env.render()

[  -7.65290331   -7.80804837   -8.034      2191.96292321  -12.36
  -12.36      ]
False
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)


In [122]:
def play_game(state, q):
    done = False
    env.render()
    while not done:
        action = np.argmax(Q[state])
        state, reward, done, info = env.step(action)
        print(reward)
        env.render()

In [123]:
s = env.reset()
play_game(s, Q)

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

-1
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
-1
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
-1
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
-1
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
-1
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
-1
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
-1
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
-1
+---------+
|R: | : :G|
| : : : : |
| : : : : |
|_| : | : |
|Y| : |B: |
+---------+
  (North)
-1
+---------+
|R: | : :G|
| : : : : |
|_: : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
-1
+---------+
|R: | : :G|
|_: : : : |
| : 

In [124]:
env.close()

In [125]:
env = gym.make("FrozenLake-v0")

In [126]:
env.reset()

0

In [127]:
env.observation_space.n

16

In [128]:
env.action_space.n

4

In [129]:
env.render()


SFFF
FHFH
FFFH
HFFG


In [130]:
Q = np.zeros([env.observation_space.n, env.action_space.n])

In [132]:
G = 0
alpha = 0.614

env.env.s = 11
env.render()


SFFF
FHFH
FFFH
HFFG


In [138]:
for episode in range(1,10):
    done = False
    G, reward = 0,0
    state = env.reset()
    while done != True:
            action = np.argmax(Q[state]) #1
            state2, reward, done, info = env.step(action) #2
            print(state2, reward, done, info)
            Q[state,action] += alpha * (reward + np.max(Q[state2]) - Q[state,action]) #3
            G += reward
            state = state2   
    if episode % 50 == 0:
        print('Episode {} Total Reward: {}'.format(episode,G))

0 0.0 False {'prob': 0.3333333333333333}
0 0.0 False {'prob': 0.3333333333333333}
0 0.0 False {'prob': 0.3333333333333333}
4 0.0 False {'prob': 0.3333333333333333}
4 0.0 False {'prob': 0.3333333333333333}
0 0.0 False {'prob': 0.3333333333333333}
0 0.0 False {'prob': 0.3333333333333333}
0 0.0 False {'prob': 0.3333333333333333}
4 0.0 False {'prob': 0.3333333333333333}
8 0.0 False {'prob': 0.3333333333333333}
8 0.0 False {'prob': 0.3333333333333333}
8 0.0 False {'prob': 0.3333333333333333}
12 0.0 True {'prob': 0.3333333333333333}
4 0.0 False {'prob': 0.3333333333333333}
0 0.0 False {'prob': 0.3333333333333333}
4 0.0 False {'prob': 0.3333333333333333}
0 0.0 False {'prob': 0.3333333333333333}
4 0.0 False {'prob': 0.3333333333333333}
8 0.0 False {'prob': 0.3333333333333333}
4 0.0 False {'prob': 0.3333333333333333}
8 0.0 False {'prob': 0.3333333333333333}
4 0.0 False {'prob': 0.3333333333333333}
4 0.0 False {'prob': 0.3333333333333333}
0 0.0 False {'prob': 0.3333333333333333}
0 0.0 False {'pr

In [134]:
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])